### ISSUE TITLE
Test dataset processing fails when using FLASH end-pairing

### ISSUE THREAD

**Issue by souptonuts** [NBISweden/IgDiscover#101]
Download igdiscover-testdata-0.6-tar.gz
Change  IgDiscover/discoverrtest/igdiscover.yaml to   **merge_program: flash**
IgDiscover run fails with the error:

> Finished job 40.
1 of 36 steps (3%) done
  rule parse_flash_stats:
    input: reads/2-flash.log
    output: stats/reads.json
    jobid: 31
 Job counts:
	count	jobs
	1	parse_flash_stats
	1
 Error in rule parse_flash_stats:
    jobid: 0
    output: stats/reads.json

> SystemExit in line 130 of /usr/local/lib/python3.6/dist-packages/igdiscover-0.12.dev68+g7f6179b-py3.6.egg/igdiscover/Snakefile:
Could not parse the FLASH log file
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
  File "/usr/local/lib/python3.6/dist-packages/igdiscover-0.12.dev68+g7f6179b-py3.6.egg/igdiscover/Snakefile", line 130, in __rule_parse_flash_stats
Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: IgDiscover/discovertest/.snakemake/log/2019-08-14T215059.922222.snakemake.log

snakemake.log has similar content

> rule parse_flash_stats:
    input: reads/2-flash.log
    output: stats/reads.json
    jobid: 31
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: IgDiscover/discovertest/.snakemake/log/2019-08-14T215059.922222.snakemake.log

The directory discovertest/stats is empty

**Comment by souptonuts** [comment]
The flash logfile error results from a typo in the Snakemake file

`    rule parse_flash_stats:
        input: log='reads/2-flash.log'
        output:
            json='stats/reads.json'
        run:
            total_ex = re.compile(r'\[FLASH\]\s***Total reads**:\s*([0-9]+)')
            merged_ex = re.compile(r'\[FLASH\]\s***Combined reads**:\s*([0-9]+)')
            with open(input.log) as f:
                for line in f:
                    match = total_ex.search(line)
                    if match:
                        total = int(match.group(1))
                        continue


The Flash logfile uses different names ("pairs" instead of "reads")

>[FLASH] Read combination statistics:
[FLASH]     **Total pairs**:      7811
[FLASH]     **Combined pairs**:   7327
[FLASH]     Uncombined pairs: 484
[FLASH]     Percent combined: 93.80%

**Comment by marcelm** [comment]
Ah, thanks for catching this! Weird, I thought this worked at some point in time ... (FLASH hasn’t made any new releases, so it cannot be that they changed their message.) We didn’t catch this because we don’t run FLASH during the tests.

I fixed the error and also added a test.
