### ISSUE TITLE
Error: No V genes were discovered in this iteration 

### ISSUE THREAD

**Issue by LandiMi2** [NBISweden/IgDiscover#103]
Hi I am getting this kind of error even if I run two iterations for my data set. I have confirmed the database V,D and J sequences match my sequences. What could be the problem, I am sure my data set should have new alleles present.

**Comment by LandiMi2** [comment]
@marcelm please help.

**Comment by marcelm** [comment]
Can you tell me a bit more about the data? How many reads do you have? Which read lengths? From which sequencer?

**Comment by marcelm** [comment]
It may also be helpful if you could show the contents of the `stats/stats.json` file that was created by IgDiscover in the analysis directory.

**Comment by LandiMi2** [comment]
{
  "version": "0.8.0",
  "reads": {
    "total": 285306,
    "merged": 272344,
    "merging_was_done": true,
    "trimmed": 272344
  },
  "iterations": [
    {
      "size": 27
    },
    {
      "size": 0,
      "gained": 0,
      "lost": 27,
      "size_pre": 0,
      "gained_pre": 0,
      "lost_pre": 27
    }
  ]
}

**Comment by LandiMi2** [comment]
actually the stat folder was generated , maybe I can  share via email the details

**Comment by LandiMi2** [comment]
Miseq sequencing platform was used

**Comment by LandiMi2** [comment]
kindly share your email address please @marcelm

**Comment by marcelm** [comment]
I see that you’re using IgDiscover 0.8, which is very old. Many bugs have been fixed since then. Can you upgrade?

You can send e-mails to marcel.martin@scilifelab.se .

**Comment by LandiMi2** [comment]
what is the new version ? 
is this how I upgrade?
$conda install igdiscover=(version)

**Comment by LandiMi2** [comment]
0.11-0 ?

**Comment by marcelm** [comment]
0.11 sounds good!  `conda update igdiscover` should work, but also `conda install igdiscover=0.11`.
