### ISSUE TITLE
Docs may need updating for J discovery

### ISSUE THREAD

**Issue by ressy** [NBISweden/IgDiscover#104]
In the [user guide for the latest stable release](http://docs.igdiscover.se/en/stable/guide.html#final-results) it says the final D and J FASTA are just copied from the input:

> final/database/(V,D,J).fasta
> 
> These three files represent the final, individualized V/D/J database found by IgDiscover. The D and J files are copies of the original starting database; they are not updated by IgDiscover.

...but in working through the test data set it does look like we get a newly-discovered J allele in the final output, which matches the j_discovery setting in the default config YAML.  Is that blurb just left over from before the J discovery feature, maybe?  (It looks like that section dates back to around 2016 but J discovery was added around 2017?)

Also, thanks for making this such a cleanly-built tool with conda/Snakemake/readthedocs and all that.  That really made setup and an initial walkthrough a breeze.

**Comment by marcelm** [comment]
Thanks for reporting! Yes, you’re right, it is correct that J discovery is always done in this version of IgDiscover, and with the default configuration, the discovered alleles are even used in subsequent iterations. I’ll see when I find some time to update the user guide. And thanks for appreciating the effort we put into the tool :-).

**Comment by ressy** [comment]
Great, thanks!
