### ISSUE TITLE
snakemake error

### ISSUE THREAD

**Issue by kokomutai** [NBISweden/IgDiscover#109]
I am trying to run igdiscover on my samples. However, l keep getting a snakemake error. This is how the error looks like:
Computing empirical frequencies....: 1 Problem, number of reads does not match! n1 = 0 n2 = 72861
Traceback (most recent call last):
  File "/Users/jmutai/anaconda2/envs/igdiscover/bin/igdiscover", line 10, in <module>
    sys.exit(main())
  File "/Users/jmutai/anaconda2/envs/igdiscover/lib/python3.7/site-packages/igdiscover/__main__.py", line 95, in main
    to_run()
  File "/Users/jmutai/anaconda2/envs/igdiscover/lib/python3.7/site-packages/igdiscover/__main__.py", line 93, in <lambda>
    to_run = lambda: subcommand(args)
  File "/Users/jmutai/anaconda2/envs/igdiscover/lib/python3.7/site-packages/igdiscover/cli/merge.py", line 109, in main
    func(path1=args.reads1, path2=args.reads2, output=args.output, threads=args.threads)
  File "/Users/jmutai/anaconda2/envs/igdiscover/lib/python3.7/site-packages/igdiscover/cli/merge.py", line 63, in run_pear
    subprocess.run(args, check=True)
  File "/Users/jmutai/anaconda2/envs/igdiscover/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pear', '-j', '4', '-f', 'reads/1-limited.1.fastq.gz', '-r', 'reads/1-limited.2.fastq.gz', '-o', PosixPath('/var/folders/24/lxszf3tj18g__4g_nm8klcvh8kgq7x/T/tmpxxdx9q6v/merged')]' died with <Signals.SIGABRT: 6>.
[Wed Mar 25 12:13:14 2020]
Error in rule pear_merge:
    jobid: 40
    output: reads/2-merged.fastq.gz, reads/2-pear.log
    log: reads/2-pear.log (check log file(s) for error message)
    shell:
        igdiscover merge -j 4 reads/1-limited.1.fastq.gz reads/1-limited.2.fastq.gz reads/2-merged.fastq.gz | tee reads/2-pear.log
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job pear_merge since they might be corrupted:
reads/2-pear.log
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/jmutai/IgDiscover/Koko/5983_2/myexperiment/.snakemake/log/2020-03-25T121301.792786.snakemake.log

Can someone tell me what could be causing the error

**Comment by marcelm** [comment]
Hi, the actual error message is a bit hidden. It is:
> Problem, number of reads does not match! n1 = 0 n2 = 72861

This error is printed by PEAR, which is the program that merges paired-end reads into single sequences. It apparently complains that one of the input files has no reads. Can you check your FASTQ files?

**Comment by kokomutai** [comment]
Hi, I have checked the FASTQ files and l found that they had been corrupted, thanks for that. Do you know if l can use igdiscover to perform longitudinal analysis?

**Comment by kokomutai** [comment]
Error in rule check_trimming:
    jobid: 0
    output: stats/trimming-successful

SystemExit in line 374 of /Users/jmutai/anaconda2/envs/igdiscover/lib/python3.7/site-packages/igdiscover/Snakefile:
1
  File "/Users/jmutai/anaconda2/envs/igdiscover/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/Users/jmutai/anaconda2/envs/igdiscover/lib/python3.7/site-packages/igdiscover/Snakefile", line 374, in __rule_check_trimming
Exiting because a job execution failed. Look above for error message
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/jmutai/IgDiscover/Koko/5983/myexperiment/.snakemake/log/2020-03-25T130511.963345.snakemake.log

This is an error after cutadpt

**Comment by marcelm** [comment]
Great, glad you found the problem. I don’t have experience with longitudinal studies. You can certainly analyze multiple samples taken at different time points with IgDiscover, but the tool does not have any built-in support for comparing these samples to each other and showing how the expression profiles develop, so that part you would have to do manually. And of course the germline V/D/J sequences shouldn’t change over time.

**Comment by marcelm** [comment]
Sorry, I commented before seeing your latest comment. I’ll reply later.

**Comment by marcelm** [comment]
The actual error message should have been printed above the one that you copied. It will probably be this error:
> Less than 10% of the input reads contain the required primer 
> sequences. Please check whether you have specified the 
> correct primer sequences in the configuration file. To skip 
> this check, create the file "stats/trimming-successful" and 
> re-start "igdiscover run".

So you should check your primers. Alternatively, don’t specify primer sequences at all – IgDiscover doesn’t really care that much whether you leave them in or not.

**Comment by kokomutai** [comment]
leaving the primers wouldn't affect the output of the analysis such as assign wrong VDJs?

**Comment by marcelm** [comment]
The effect, if any, should be small.

IgBLAST, which IgDiscover uses to make the V/D/J assignments, ignores any sequence upstream of the V and downstream of the J anyway. Whether that sequence includes the primers or not should therefore not influence the assignments.

However, when you specify primers to remove, IgDiscover also removes all sequences that don’t have the primers. So if you don’t specify them, there’ll be some extra sequences that would otherwise not be analyzed. I haven’t tested how much this affects the results, but all the testing I do is without specifying primer sequences.

**Comment by kokomutai** [comment]
Thank you Martin, i also noticed the dendograms aren't as pretty. I tried using dendroscope, but there's no file from igdiscover that can be used in dendroscope. I waould like to draw the circular tress. Any program you know of that can input files from IgDiscover?

**Comment by marcelm** [comment]
Well, beauty is in the eye of the beholder – I like the dendrograms ;-).

In earnest: The dendrograms exist only as a way to get a quick overview, and I’m certain they could be improved.

I searched just now for a way to save the tree that is computed in Newick format, but haven’t found an easy way. Feel free to submit that as a feature request (in a separate issue).

At the moment, if you want a prettier visualization, you’ll need to recompute the tree yourself using `iteration-01/new_V_germline.fasta` as input.

**Comment by kokomutai** [comment]
Thank you Marcel :-)

**Comment by marcelm** [comment]
I believe the issue has been resolved, so I’m closing it now.
