### ISSUE TITLE
IgDiscover crashes if no arguments are given

### ISSUE THREAD

**Issue by ressy** [NBISweden/IgDiscover#110]
This is a very minor issue but I noticed in the latest stable version (0.12.3) that if no command-line arguments are given, the igdiscover command crashes before it reaches the expected error message.

```
$ igdiscover 
Traceback (most recent call last):
  File "/home/jesse/miniconda3/envs/example-igdiscover/bin/igdiscover", line 10, in <module>
    sys.exit(main())
  File "/home/jesse/miniconda3/envs/example-igdiscover/lib/python3.8/site-packages/igdiscover/__main__.py", line 85, in main
    del args.func
AttributeError: func
```

I'm thinking the `del args.func` [here](https://github.com/NBISweden/IgDiscover/blob/264601c06244b3830ce75e98d972ededb55b7b48/src/igdiscover/__main__.py#L85) should probably be conditional on the value of `subcommand`, so you get the 'Please provide the name of a subcommand to run' message a few lines below?

**Comment by marcelm** [comment]
Thanks, you are right! That should be fixed now.
