### ISSUE TITLE
Solving environment: failed

### ISSUE THREAD

**Issue by pursellta** [NBISweden/IgDiscover#116]
I am trying to install IgDiscover and am having issues; I have tried both on my Mac and on a linux server. I installed miniconda (version 4.10.3) and followed the instructions on the installation page to the letter and I keep getting this error:

**Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: -** 

And then it never finishes. I have tried making the channel order flexible as well as creating the environment separately, activating it, and then trying to install. I can't seem to get it to work.

**Comment by marcelm** [comment]
This could be a transient failure, so you may just need to try again, but you can also try to use mamba instead of conda: "conda install mamba", then write "mamba" instead of "conda" when installing IgDiscover.

**Comment by pursellta** [comment]
> This could be a transient failure, so you may just need to try again, but you can also try to use mamba instead of conda: "conda install mamba", then write "mamba" instead of "conda" when installing IgDiscover.

I tried again and it didn't work. The "mamba" work around seems to have solved the problem though so thank you!
