### ISSUE TITLE
Improve CDR3 detection by using a more recent IgBLAST

### ISSUE THREAD

**Issue by marcelm** [NBISweden/IgDiscover#12]
The CDR3 detection regular expression by D'Addario et al. that we use is roughly like this `[FY] [FHVWY] C ... W [AGV]` (the `...` is the CDR3, the things to the left and right are allowed amino acids). However, we do not detect some CDR3s with it. For example, in one of the datasets, the `C` is mutated and becomes a `W`.

**Comment by marcelm** [comment]
A new IgBLAST version is going to be released soon (one newer than 1.6.1) which should report CDR3 coordinates.

**Comment by marcelm** [comment]
IgBLAST 1.7.0 is out. According to [the changelog](ftp://ftp.ncbi.nih.gov/blast/executables/igblast/release/1.7.0/ChangeLog), it should finally output CDR3 start and stop coordinates:

> April 19, 2017
> *Make nucleotide overlaps at VDJ junctions an option (-allow_vdj_overlap) and default is set to no overlap allowed.  Previous versions were hard-coded to allow nucleotide overlaps at VDJ junctions.
> *Use alignment length instead of percent identity as tiebreaker for hits with identical blast scores.
> *Allow custom J gene mismatch penalty.
> *Add CDR3 start and stop to sub-region table

**Comment by marcelm** [comment]
To determine CDR3 coordinates, IgBLAST needs an auxiliary table that describes where in the J the CDR3 ends.

**Comment by willbradshaw** [comment]
Hi,

Any chance of this being implemented in IgDiscover in the future? Possibly because I'm working in a non-mammalian system, the regex method currently used by IgDiscover seems to give much lower rates of successful CDR3 assignment (~15% of reads) than I get when I run IgBLAST directly with my auxiliary file in my other pipelines. :)

**Comment by marcelm** [comment]
IgBLAST didn’t report accurate CDR3 locations until a while ago, and when it started to do so, that information wasn’t part of the text output that IgDiscover needs. The most recent IgBLAST version supposedly has that information now, but I have so far not had time to look into integrating this into IgDiscover.

And since I haven’t commented here in a while: We’ve actually updated the CDR3 discovery code in IgDiscover recently. It doesn’t use regular expressions on the reads anymore. Instead, they are applied on the database V and J sequences in order to detect the CDR3 start and end. These locations are then used to derive where the CDR3 is in each read after IgBLAST gives us the V and J locations. This improved the CDR3 detection rate (on mammalian species) to something upwards of 98%.

**Comment by willbradshaw** [comment]
Okay, thanks. Maybe this should go in a different topic, then, but: do you have any suggestion for how to handle this when the CDR3 detection doesn't work well? I'm consistently getting 10-15% of my merged reads assigned CDR3s, which I can't imagine is good for my discovery results.

**Comment by MartinMatthewC** [comment]
Hi Will,
Are you sure this a CDR3 issue and not a library issue?
What I mean is, are you sure that the library is specific for IG sequences, or is there a lot of non IG sequences being amplified too?
Martin

________________________________

**Comment by willbradshaw** [comment]
Hi Martin,
It's a fair question, and not one that's answered directly by my current processing pipeline. As a quick and simple test I tried aligning my raw read sets to my V-library with bowtie2 under standard parameters, and about 75% of reads aligned to at least one V in my library. I think this is probably an underestimate of the proportion of reads that are actually IgM, but even if that's not the case it's a lot higher than 15%.

**Comment by MartinMatthewC** [comment]
Hi Will,
Yes, that sounds like your libraries are probably OK.
I have been able to use IgDiscover with zebrafish libraries in the past so it has been able to handle non mammalian cdr3s however it may be that you have a species where the cdr3s are sufficiently different that they are not recognized.
One quick test that we sometimes do is to take a sequence where IgDiscover fails to detect a cdr3 and put the same sequence into the online IgBLAST (the default human database is usually fine for this test) and see if a cdr3 is detected. If a cdr3 is detected here then it may point out some additional cdr3 sequence motifs that we may need to include in the IgDiscover cdr3 detection process.

Martin
________________________________

**Comment by marcelm** [comment]
@willbradshaw How did you determine that a CDR3 was detected in only 15% of your sequences? The relevant lines in the log would be these:
```
INFO: 1234 IgBLAST assignments parsed and written
INFO: CDR3s detected in 90.8% of all sequences
```
Did you set the `barcode_length_5p` or `barcode_length_3p` options? Then there’s another CDR3 detection step which uses the old less reliable regex.

If you translate your V and J database sequences to amino acids, you can check yourself whether the CDR3 detection regexes have a chance of working.

For heavy chains, the CDR3 start is detected within the translated V with the regex `[FY] [FHVWY] C [ADEGIKMNRSTV]` (if that does not work, then `C.[RK]` is used). The CDR3 end is detected within the translated J (all frames are checked) by `W[GAV]`.

You can see the regexes for the other chains [directly in the code for V](https://github.com/NBISweden/IgDiscover/blob/c7a9d02e0ddaea7689872704afdd59857cc4921e/igdiscover/species.py#L98) and [also for J](https://github.com/NBISweden/IgDiscover/blob/c7a9d02e0ddaea7689872704afdd59857cc4921e/igdiscover/species.py#L148).

If you want, you can (privately) send me your V/D/J.fasta files so I could take a look. IgDiscover unfortunately doesn’t yet print out for which database sequences it couldn’t find CDR3 start/stop coordinates.

**Comment by marcelm** [comment]
This repository is outdated and is going to be archived. Please see the new repository at https://gitlab.com/gkhlab/igdiscover22/ or the homepage at https://www.igdiscover.se/ for the most recent and maintained IgDiscover version.
