### ISSUE TITLE
Cannot install IgDiscover on M1 MacBook Pro

### ISSUE THREAD

**Issue by kllenart** [NBISweden/IgDiscover#120]
I have a MacBook Pro (13-inch, M1, 2020) with Apple M1 processor. Installation of Bioconda and the channels was successful. When I follow the installation instructions on the website I get the following error:
<img width="827" alt="IgDiscover install failed" src="https://user-images.githubusercontent.com/104560874/207935436-1b4f91f9-d9eb-48dc-93fe-a5f9c4469236.png">

**Comment by marcelm** [comment]
Hi Klara, I think the problem is that Bioconda does not provide native packages for the M1 processor. However, you can tell it [to use the packages built for x86 Macs](https://stackoverflow.com/a/71554275/715090) using a "subdir" setting and that appears to work.

I think this may work:
```bash
CONDA_SUBDIR=osx-64 conda create -n igdiscover igdiscover
```

**Comment by kllenart** [comment]
Hi Marcel,

thank you for a quick reply, this worked and I managed to install it!

**Comment by marcelm** [comment]
Oh great to know! I have updated the installation instructions to reflect this.
