### ISSUE TITLE
trouble installing with conda

### ISSUE THREAD

**Issue by john-dingus** [NBISweden/IgDiscover#123]
I am trying to install IgDiscover with conda according to the IgDiscover documentation, and have tried several versions of both conda and python, but the environment always fails to solve. Is IgDiscover still supported by conda? Is there a trick to solving the installation? 
Thanks,
John

**Comment by marcelm** [comment]
Can you be more specific? Which exact command(s) are you using and which error messages do you get?

**Comment by marcelm** [comment]
This repository is outdated and is going to be archived. Please see the new repository at https://gitlab.com/gkhlab/igdiscover22/ or the homepage at https://www.igdiscover.se/ for the most recent and maintained IgDiscover version.
