### ISSUE TITLE
What is CDR3_shared_ratio

### ISSUE THREAD

**Issue by carollia** [NBISweden/IgDiscover#98]
Hi,

I was going through the results of my assigned_V_pregermline.tab and assigned V_germline.tab and a number of candidates were filtered out because of a high CDR3_shared_ratio. I've tried to figure out what this means and how it's calculated but I cannot. Can you tell me what it means and how it is calculated?

Thanks,
Hannah

**Comment by MartinMatthewC** [comment]
Hi Carollia,

The cdr3_shared ratio is meant as a type of indirect means of identifying chimeric sequences and of filtering them from the output. It is designed to identify unique CDR3 sequences from one rearrangement and then identifying the same CDR3 sequence in other allele - indicating that there may be some kind of chimerism event during library PCR.

In general chimeric events tend to occur at a low rate and are generally removed by the allelic ratio filter but the cdr3_shared ratio can be useful in some circumstances..

However, while this filter can identify and remove chimeric sequences we have noticed recently that it will also remove some sequences that are real germlines so to avoid this we tend to set a very high setting to minimize this problem (for example, set cdr3_shared_ratio: 0.99).

Martin

________________________________

**Comment by marcelm** [comment]
This repository is outdated and is going to be archived. Please see the new repository at https://gitlab.com/gkhlab/igdiscover22/ or the homepage at https://www.igdiscover.se/ for the most recent and maintained IgDiscover version.
